spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
          min-idle: 5
          max-wait: -1ms
        shutdown-timeout: 100ms

logging:
  level:
    kr.hhplus.be.server: DEBUG
    kr.hhplus.be.server.infrastructure.adapter.out.persistence.lock: DEBUG
    org.redisson: WARN
    io.lettuce: WARN
    org.springframework.data.redis: WARN
    org.testcontainers: INFO