package kr.hhplus.be.server.application.saga.payment

enum class PaymentSagaState {
    STARTED,
    POINT_DEDUCTING,
    POINT_DEDUCTED,
    SEAT_CONFIRMING,
    SEAT_CONFIRMED,
    RESERVATION_CONFIRMING,
    RESERVATION_CONFIRMED,
    PAYMENT_CREATING,
    PAYMENT_CREATED,
    COMPLETED,
    COMPENSATING,
    POINT_REFUNDING,
    POINT_REFUNDED,
    SEAT_RELEASING,
    SEAT_RELEASED,
    RESERVATION_CANCELLING,
    RESERVATION_CANCELLED,
    COMPENSATED,
    FAILED
}